const cardDetails = [
  {
    id: 1,
    title: "Crud Table",
    description:
      "Simple crud table with search, filter and pagination features",
    link: " https://frontend-rookie-crud-table.netlify.app/",
    pulseColor: "#dc3545",
    background: "#ffffe0",
    activeColor: "#ffc107",
    hoverTextColor: "#212529",
  },
  {
    id: 2,
    title: "Shopping Cart",
    description:
      "Shopping cart implemented using Redux and dummy API endpoints ",
    pulseColor: "#dc3545",
    background: "#ffffe0",
    activeColor: "#ffc107",
    hoverTextColor: "#212529",

    link: "https://frontend-rookie-shopping-cart.netlify.app/",
  },
  {
    id: 3,
    title: "Scroll Indicator",
    description: "Simple CRUD table with search and pagination features",
    pulseColor: "#dc3545",
    background: "#ffffe0",
    activeColor: "#ffc107",
    color: "#212529",
    link: "https://frontend-rookie-scroll-indicator.netlify.app/",
  },
  {
    id: 4,
    title: "College Website",
    description: "A basic website for an academic institution... ",
    link: "https://frontend-rokie-college-website.netlify.app/",
    pulseColor: "#dc3545",
    background: "#ffffe0",
    activeColor: "#ffc107",
    color: "#212529",
  },
  {
    id: 5,
    title: "Meme Generator",
    description:
      "The Meme generator is an app that enables user to generate meme, upload files, generate colors and also download their files",
    link: "https://monkz-meme-generator.netlify.app/",
    pulseColor: "#28a745",
    background: "#ffffe0",
    activeColor: "#ffc107",
    color: "#212529",
  },
  {
    id: 6,
    title: "Sound-pads",
    description:
      "This React app. It was implemented using useState hook in React",
    link: "https://frontend-rookie-sound-pads.netlify.app/",
    pulseColor: "#28a745",
    background: "#ffffe0",
    activeColor: "#ffc107",
    color: "#212529",
  },
  {
    id: 7,
    title: "Dashboard",
    description: "Simple dashboard table with search and pagination features",
    link: "https://frontend-rookie-dashbord.netlify.app/",
    pulseColor: "#28a745",
    background: "#ffffe0",
    activeColor: "#ffc107",
    color: "#212529",
  },
  {
    id: 8,
    title: "Credit Card app",
    description: "The Credit card app allows users to edit card details",
    link: "https://my-credit-card-app.netlify.app/",
    pulseColor: "#28a745",
    background: "#ffffe0",
    activeColor: "#ffc107",
    color: "#212529",
  },
  {
    id: 9,
    title: "Dynamic form",
    description:
      "Dynamic form app that allowa extra form inputs can be removed or added. ",
    link: "https://frontend-rookie-dynamic-input-fields.netlify.app/",
    pulseColor: "#dc3545",
    background: "#ffffe0",
    activeColor: "#ffc107",
    color: "#212529",
  },
  {
    id: 10,
    title: "Multi-step form",
    link: "https://forntend-rookie-multistep-form.netlify.app/",
    description: "A multi-step form implemented in React.",
    pulseColor: "#dc3545",
    background: "#ffffe0",
    activeColor: "#ffc107",
    color: "#212529",
  },
  {
    id: 11,
    title: "Admin Dashboard",
    link: "https://rookie-admin-dashboard.netlify.app/",
    description:
      "Admin dashboard with Charts, Search and theme changing features ",
    pulseColor: "#28a745",
    background: "#ffffe0",
    activeColor: "#ffc107",
    color: "#212529",
  },
  {
    id: 12,
    title: "Upcoming Projects",
    description: "For more projects... ",
    link: "https://github.com/Layomi1",
    pulseColor: "",
    background: "#fff",
    activeColor: "#fff",
    color: "#ffc107",
  },
];
export default cardDetails;
